# Generated by Django 5.0 on 2023-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_signup', '0003_remove_imagemodel_user_imagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
