# Generated by Django 5.0 on 2023-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_signup', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
