# Generated by Django 5.0 on 2023-12-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_signup', '0005_imagemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='created_at',
        ),
    ]
