# Generated by Django 5.0 on 2023-12-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_signup', '0007_rename_image_imagemodel_image_file_imagemodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='title',
        ),
    ]
